# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

exclude: [fix_md_script]

# Site settings
title:
  en: VoxForge - Free Speech... Recognition
  es: VoxForge - libertad de expresión
  fr: VoxForge - Voix Libre
  de: VoxForge - Freie Spracherkennung
  ht: VoxForge - Libere konesans lapawòl

# word 'language' in local language
languagesLocal:
  en: Languages
  fr: Langues
  es: Idiomas
  de: Sprache
  ht: Lang


# localized language name
languageName:
  en: English
  fr: Français
  es: Español
  de: Deutsche
  ht: Kreyòl

# hover language name translated to English
languageEnglish:
  en: English
  fr: French
  es: Spanish
  de: German
  ht: Haitian Creole

email: pierevans@gmail.com

# home page
index:
  en: home
  fr: accueil
  es: boenosdias
  de: startseite
  ht: akèy

baseurl: "" # the subpath of your site, e.g. /blog

# redirects use this url:
#url: "https://voxforge.github.io" # prod - the base hostname & protocol for your site
url: "https://jekyll_voxforge.org" # dev - (need to also update voxforge_sw.js and _config.yml: permalink)
                                   # use https://jekyll_voxforge.org/en/read/ to directly access read page

# add trailing slash to permalinks:
# (for debugging with Apache2 and self signed SSL certificate)
# note: messes up manifest path,
permalink: /:lang/:ref # prod - required for links to work properly on Github
#permalink: /:lang/:ref/ # dev - (need to also update voxforge_sw.js and _config.yml: URL; and copy manifest file to en/read and restart jekyll...)


collections:
  faqs:
    output: true
    title: FAQs

# see: https://help.github.com/articles/redirects-on-github-pages/
#plugins:
#  - jekyll-redirect-from

